# Generated by Django 4.2.6 on 2023-10-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='desciption',
            new_name='description',
        ),
    ]
